---
title: "Econometria I"
author: "Marcos J Ribeiro"
date: "11/08/2020"
output:
  slidy_presentation: default
  beamer_presentation:
    colortheme: dolphin
    fonttheme: structurebold
    slide_level: 2
    theme: AnnArbor
institute: FEARP-USP
fontsize: 10pt
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Porque utilizar o R?

- Os pilares da Econometria
- Linguagem de programação voltada para estatística
- Muitos usuários
- APIs
- [Rmarkdown](https://rmarkdown.rstudio.com/index.html) e integração com o \LaTeX
- Rpubs
- Bibliotecas (Neural Net, Nimble, rjags, Caret, ggplot2, rugarch...)
- Integração com outras linguagens (Python, SQL, C++, HTML, Markdown...)
- Grandes indústrias utilizam
- Sua carreira está ameaçada se você não sabe programar

## Como obter ajuda?

- Tecla F1
- ?comando
- Stack Overflow
- Rblogs
- [Livros](https://bookdown.org/ccolonescu/RPoE4/), cursos 
- [Rseek](https://rseek.org/)
- [GitHub](https://github.com/mj-ribeiro/Econometry) 


## Estrutura do curso

- print, cat
- Variáveis
- Operações
- Vetores e matrizes (rbind, cbind)
- rep, seq
- Operações com matrizes  
- Data frames
- Booleanos
- Fatiamento
- Como resolver o inconveniente e chato problema do Nan



## Estrutura do curso

- Condicionais (if, else, ifelse)
- Loops (for, while)
- Contadores e acumuladores
- Funções
- plots
- APIs
- Rmarkdown


## Estrutura do curso

- Distribuições estatísticas
- MQO
- MQG
- Testes estatísticos
- Multicolinearidade
- Autocorrelação
- Heterocedasticidade
- Especificação de modelo e teste de diagnóstico


## Exercícios 

- Exercício 1: Regressão Linear
- Exercício 2: Lei dos Grandes números
- Exercício 3: Integral definida utilizando Método de Monte Carlo
- Exercício 4: Simulando o lançamento de uma moeda
- Exercício 5: Teorema de Gauss-Markov
- Exercício 6: Análise de dados


## Contato

- [GitHub](https://github.com/mj-ribeiro)   
- [Website](https://mj-ribeiro.github.io/)  
- email: mjribeiro@usp.br



